
version: '3'

services:

  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    environment:
      - EXTRA=1
    restart: always
    ports:
      - 127.0.0.1:9306:9306
      - 127.0.0.1:9308:9308

  rabbitmq:
      image: rabbitmq:3.12.4-management-alpine
      container_name: "rabbitmq"
      ports:
          - 5672:5672
          - 15672:15672
      environment:
          - RABBITMQ_NODENAME=node@rabbitmq
      volumes:
          - rabbitmq_data:/var/lib/rabbitmq/
          - rabbitmq_logs:/var/log/rabbitmq


volumes:
  manticore_data:
  rabbitmq_data:
  rabbitmq_logs:
