package geolabels

var countryCodeToLanguages = map[string][]string{
	"tw": {"zh"},
	"ua": {"uk"},
	"zw": {"en", "sn", "nd"},
	"cm": {"en", "fr"},
	"il": {"he", "ar"},
	"lb": {"ar", "fr"},
	"lk": {"si", "ta"},
	"mw": {"en", "ny"},
	"ad": {"ca"},
	"ck": {"en"},
	"ir": {"fa"},
	"mf": {"en", "fr", "nl"},
	"mo": {"zh", "pt"},
	"cl": {"es"},
	"cw": {"nl", "pa", "en"},
	"jp": {"ja"},
	"kp": {"ko"},
	"ar": {"es", "gn"},
	"mt": {"mt", "en"},
	"tl": {"pt"},
	"ao": {"pt"},
	"as": {"en", "sm"},
	"eh": {"es"},
	"hn": {"es"},
	"fo": {"fo"},
	"th": {"th"},
	"tv": {"en"},
	"ae": {"ar"},
	"bw": {"en", "tn"},
	"mm": {"my"},
	"ps": {"ar"},
	"bb": {"en"},
	"ms": {"en"},
	"sj": {"no"},
	"sr": {"nl"},
	"tn": {"ar"},
	"ug": {"en", "sw"},
	"gq": {"es", "fr"},
	"kg": {"ky", "ru"},
	"sk": {"sk"},
	"so": {"so", "ar"},
	"gn": {"fr", "ff"},
	"my": {"ms"},
	"ro": {"ro"},
	"sh": {"en"},
	"cd": {"fr", "ln", "kg", "sw", "lu"},
	"io": {"en"},
	"pt": {"pt"},
	"rw": {"rw", "en", "fr"},
	"bn": {"ms"},
	"cu": {"es"},
	"mr": {"ar"},
	"re": {"fr"},
	"vi": {"en"},
	"gd": {"en"},
	"gw": {"pt"},
	"dz": {"ar"},
	"pf": {"fr"},
	"pn": {"en"},
	"sa": {"ar"},
	"zm": {"en"},
	"cc": {"en"},
	"sv": {"es"},
	"td": {"fr", "ar"},
	"tr": {"tr"},
	"bl": {"fr"},
	"co": {"es"},
	"cx": {"en"},
	"gb": {"en"},
	"nc": {"fr"},
	"de": {"de"},
	"ke": {"en", "sw"},
	"ly": {"ar"},
	"af": {"ps", "uz", "tk"},
	"aw": {"nl", "pa"},
	"ca": {"en", "fr"},
	"me": {"sr", "bs", "sq", "hr"},
	"bv": {"no", "nb", "nn"},
	"kr": {"ko"},
	"lr": {"en"},
	"vn": {"vi"},
	"gs": {"en"},
	"id": {"id"},
	"to": {"en", "to"},
	"za": {"af", "en", "nr", "st", "ss", "tn", "ts", "ve", "xh", "zu"},
	"bo": {"es", "ay", "qu"},
	"mk": {"mk"},
	"mq": {"fr"},
	"us": {"en"},
	"ml": {"fr"},
	"nr": {"en", "na"},
	"vc": {"en"},
	"ye": {"ar"},
	"ai": {"en"},
	"ax": {"sv"},
	"gr": {"el"},
	"py": {"es", "gn"},
	"is": {"is"},
	"mv": {"dv"},
	"wf": {"fr"},
	"gp": {"fr"},
	"mh": {"en", "mh"},
	"se": {"sv"},
	"bt": {"dz"},
	"gh": {"en"},
	"aq": {""},
	"ky": {"en"},
	"nz": {"en", "mi"},
	"tt": {"en"},
	"br": {"pt"},
	"jo": {"ar"},
	"xk": {"sq", "sr"},
	"na": {"en", "af"},
	"st": {"pt"},
	"ba": {"bs", "hr", "sr"},
	"cr": {"es"},
	"hk": {"zh", "en"},
	"mz": {"pt"},
	"az": {"az"},
	"cy": {"el", "tr", "hy"},
	"mn": {"mn"},
	"bs": {"en"},
	"ru": {"ru"},
	"ec": {"es"},
	"gy": {"en"},
	"ni": {"es"},
	"pe": {"es"},
	"tz": {"sw", "en"},
	"hm": {"en"},
	"pm": {"fr"},
	"pr": {"es", "en"},
	"sx": {"nl", "en"},
	"ag": {"en"},
	"ge": {"ka"},
	"mp": {"en", "ch"},
	"nl": {"nl"},
	"ne": {"fr"},
	"sz": {"en", "ss"},
	"sc": {"fr", "en"},
	"bz": {"en", "es"},
	"dk": {"da"},
	"dm": {"en"},
	"ng": {"en"},
	"bj": {"fr"},
	"si": {"sl"},
	"cz": {"cs"},
	"vu": {"bi", "en", "fr"},
	"al": {"sq"},
	"ga": {"fr"},
	"lt": {"lt"},
	"sd": {"ar", "en"},
	"um": {"en"},
	"et": {"am"},
	"hu": {"hu"},
	"in": {"hi", "en"},
	"sg": {"en", "ms", "ta", "zh"},
	"lc": {"en"},
	"nf": {"en"},
	"rs": {"sr"},
	"am": {"hy", "ru"},
	"bg": {"bg"},
	"fj": {"en", "fj", "hi", "ur"},
	"ht": {"fr", "ht"},
	"pk": {"en", "ur"},
	"va": {"it", "la"},
	"ws": {"sm", "en"},
	"fk": {"en"},
	"la": {"lo"},
	"md": {"ro"},
	"pw": {"en"},
	"dj": {"fr", "ar"},
	"tm": {"tk", "ru"},
	"pg": {"en"},
	"ci": {"fr"},
	"je": {"en", "fr"},
	"kh": {"km"},
	"no": {"no", "nb", "nn"},
	"cn": {"zh"},
	"gt": {"es"},
	"im": {"en", "gv"},
	"sn": {"fr"},
	"tf": {"fr"},
	"fm": {"en"},
	"gm": {"en"},
	"kz": {"kk", "ru"},
	"tc": {"en"},
	"sl": {"en"},
	"tj": {"tg", "ru"},
	"gu": {"en", "ch", "es"},
	"jm": {"en"},
	"lu": {"fr", "de", "lb"},
	"nu": {"en"},
	"at": {"de"},
	"er": {"ti", "ar", "en"},
	"sm": {"it"},
	"fr": {"fr"},
	"it": {"it"},
	"ki": {"en"},
	"mu": {"en"},
	"au": {"en"},
	"tk": {"en"},
	"ls": {"en", "st"},
	"sy": {"ar"},
	"be": {"nl", "fr", "de"},
	"cg": {"fr", "ln"},
	"do": {"es"},
	"hr": {"hr"},
	"qa": {"ar"},
	"uy": {"es"},
	"yt": {"fr"},
	"by": {"be", "ru"},
	"kn": {"en"},
	"om": {"ar"},
	"ss": {"en"},
	"sb": {"en"},
	"bh": {"ar"},
	"cf": {"fr", "sg"},
	"ma": {"ar"},
	"mx": {"es"},
	"bf": {"fr", "ff"},
	"kw": {"ar"},
	"bm": {"en"},
	"mg": {"fr", "mg"},
	"pa": {"es"},
	"tg": {"fr"},
	"uz": {"uz", "ru"},
	"fi": {"fi", "sv"},
	"ie": {"ga", "en"},
	"lv": {"lv"},
	"np": {"ne"},
	"mc": {"fr"},
	"bd": {"bn"},
	"bq": {"nl"},
	"gl": {"kl"},
	"li": {"de"},
	"ch": {"de", "fr", "it"},
	"es": {"es", "eu", "ca", "gl", "oc"},
	"gi": {"en"},
	"ph": {"en"},
	"vg": {"en"},
	"bi": {"fr", "rn"},
	"gf": {"fr"},
	"pl": {"pl"},
	"ve": {"es"},
	"iq": {"ar", "ku"},
	"km": {"ar", "fr"},
	"cv": {"pt"},
	"ee": {"et"},
	"eg": {"ar"},
	"gg": {"en", "fr"},
}
