package geolabels

var countryLabelToCode = map[string]string{
	"united kingdom":                   "gb",
	"syria":                            "sy",
	"سوريا":                            "sy",
	"bermuda":                          "bm",
	"mali":                             "ml",
	"brunei":                           "bn",
	"negara brunei darussalam":         "bn",
	"british indian ocean territory":   "io",
	"iceland":                          "is",
	"ísland":                           "is",
	"panama":                           "pa",
	"panamá":                           "pa",
	"palau":                            "pw",
	"spain":                            "es",
	"españa":                           "es",
	"jordan":                           "jo",
	"الأردن":                           "jo",
	"sri lanka":                        "lk",
	"śrī laṃkāva":                      "lk",
	"macao":                            "mo",
	"澳門":                               "mo",
	"peru":                             "pe",
	"perú":                             "pe",
	"senegal":                          "sn",
	"sénégal":                          "sn",
	"thailand":                         "th",
	"ประเทศไทย":                        "th",
	"anguilla":                         "ai",
	"gambia":                           "gm",
	"indonesia":                        "id",
	"lebanon":                          "lb",
	"لبنان":                            "lb",
	"norway":                           "no",
	"norge":                            "no",
	"niue":                             "nu",
	"niuē":                             "nu",
	"democratic republic of the congo": "cd",
	"république démocratique du congo": "cd",
	"guernsey":                         "gg",
	"mongolia":                         "mn",
	"монгол улс":                       "mn",
	"antigua and barbuda":              "ag",
	"angola":                           "ao",
	"aruba":                            "aw",
	"costa rica":                       "cr",
	"guinea-bissau":                    "gw",
	"guiné-bissau":                     "gw",
	"south korea":                      "kr",
	"대한민국":                             "kr",
	"mauritius":                        "mu",
	"maurice":                          "mu",
	"lesotho":                          "ls",
	"germany":                          "de",
	"deutschland":                      "de",
	"saint kitts and nevis":            "kn",
	"sweden":                           "se",
	"sverige":                          "se",
	"republic of the congo":            "cg",
	"république du congo":              "cg",
	"saint martin":                     "mf",
	"saint-martin":                     "mf",
	"svalbard and jan mayen":           "sj",
	"svalbard og jan mayen":            "sj",
	"south sudan":                      "ss",
	"austria":                          "at",
	"österreich":                       "at",
	"djibouti":                         "dj",
	"comoros":                          "km",
	"komori":                           "km",
	"pitcairn islands":                 "pn",
	"tajikistan":                       "tj",
	"тоҷикистон":                       "tj",
	"tunisia":                          "tn",
	"تونس":                             "tn",
	"cook islands":                     "ck",
	"western sahara":                   "eh",
	"الصحراء الغربية":                  "eh",
	"botswana":                         "bw",
	"cayman islands":                   "ky",
	"nicaragua":                        "ni",
	"saint helena":                     "sh",
	"ukraine":                          "ua",
	"україна":                          "ua",
	"antarctica":                       "aq",
	"kyrgyzstan":                       "kg",
	"кыргызстан":                       "kg",
	"montenegro":                       "me",
	"црна гора":                        "me",
	"myanmar (burma)":                  "mm",
	"မြန်မာ":                           "mm",
	"egypt":                            "eg",
	"مصر‎":                             "eg",
	"french guiana":                    "gf",
	"guyane française":                 "gf",
	"montserrat":                       "ms",
	"suriname":                         "sr",
	"eswatini":                         "sz",
	"brazil":                           "br",
	"brasil":                           "br",
	"chile":                            "cl",
	"cyprus":                           "cy",
	"κύπρος":                           "cy",
	"france":                           "fr",
	"grenada":                          "gd",
	"niger":                            "ne",
	"saudi arabia":                     "sa",
	"العربية السعودية":                 "sa",
	"chad":                             "td",
	"tchad":                            "td",
	"vatican city":                     "va",
	"vaticano":                         "va",
	"wallis and futuna":                "wf",
	"wallis et futuna":                 "wf",
	"bouvet island":                    "bv",
	"bouvetøya":                        "bv",
	"uruguay":                          "uy",
	"aland":                            "ax",
	"åland":                            "ax",
	"falkland islands":                 "fk",
	"mozambique":                       "mz",
	"moçambique":                       "mz",
	"albania":                          "al",
	"shqipëria":                        "al",
	"equatorial guinea":                "gq",
	"guinea ecuatorial":                "gq",
	"jamaica":                          "jm",
	"kenya":                            "ke",
	"yemen":                            "ye",
	"اليَمَن":                          "ye",
	"kuwait":                           "kw",
	"الكويت":                           "kw",
	"morocco":                          "ma",
	"المغرب":                           "ma",
	"sao tome and principe":            "st",
	"são tomé e príncipe":              "st",
	"benin":                            "bj",
	"bénin":                            "bj",
	"belize":                           "bz",
	"haiti":                            "ht",
	"haïti":                            "ht",
	"lithuania":                        "lt",
	"lietuva":                          "lt",
	"vietnam":                          "vn",
	"việt nam":                         "vn",
	"bolivia":                          "bo",
	"belarus":                          "by",
	"белару́сь":                        "by",
	"isle of man":                      "im",
	"turkey":                           "tr",
	"türkiye":                          "tr",
	"belgium":                          "be",
	"belgië":                           "be",
	"georgia":                          "ge",
	"საქართველო":                       "ge",
	"east timor":                       "tl",
	"timor-leste":                      "tl",
	"bahrain":                          "bh",
	"‏البحرين":                         "bh",
	"faroe islands":                    "fo",
	"føroyar":                          "fo",
	"oman":                             "om",
	"عمان":                             "om",
	"venezuela":                        "ve",
	"china":                            "cn",
	"中国":                               "cn",
	"ireland":                          "ie",
	"éire":                             "ie",
	"malaysia":                         "my",
	"french polynesia":                 "pf",
	"polynésie française":              "pf",
	"saint vincent and the grenadines": "vc",
	"zimbabwe":                         "zw",
	"central african republic":         "cf",
	"ködörösêse tî bêafrîka":           "cf",
	"finland":                          "fi",
	"suomi":                            "fi",
	"south georgia and the south sandwich islands": "gs",
	"south georgia":            "gs",
	"india":                    "in",
	"भारत":                     "in",
	"libya":                    "ly",
	"‏ليبيا":                   "ly",
	"norfolk island":           "nf",
	"tonga":                    "to",
	"ivory coast":              "ci",
	"côte d'ivoire":            "ci",
	"dominican republic":       "do",
	"república dominicana":     "do",
	"fiji":                     "fj",
	"cambodia":                 "kh",
	"kâmpŭchéa":                "kh",
	"saint lucia":              "lc",
	"solomon islands":          "sb",
	"san marino":               "sm",
	"burkina faso":             "bf",
	"greenland":                "gl",
	"kalaallit nunaat":         "gl",
	"hong kong":                "hk",
	"香港":                       "hk",
	"papua new guinea":         "pg",
	"papua niugini":            "pg",
	"israel":                   "il",
	"יִשְׂרָאֵל":               "il",
	"australia":                "au",
	"cocos (keeling) islands":  "cc",
	"switzerland":              "ch",
	"schweiz":                  "ch",
	"curacao":                  "cw",
	"curaçao":                  "cw",
	"guadeloupe":               "gp",
	"iran":                     "ir",
	"ایران":                    "ir",
	"denmark":                  "dk",
	"danmark":                  "dk",
	"ethiopia":                 "et",
	"ኢትዮጵያ":                    "et",
	"new zealand":              "nz",
	"portugal":                 "pt",
	"el salvador":              "sv",
	"turks and caicos islands": "tc",
	"andorra":                  "ad",
	"bahamas":                  "bs",
	"cameroon":                 "cm",
	"ecuador":                  "ec",
	"guam":                     "gu",
	"marshall islands":         "mh",
	"m̧ajeļ":                   "mh",
	"nigeria":                  "ng",
	"jersey":                   "je",
	"sierra leone":             "sl",
	"trinidad and tobago":      "tt",
	"martinique":               "mq",
	"maldives":                 "mv",
	"united arab emirates":     "ae",
	"دولة الإمارات العربية المتحدة": "ae",
	"reunion":                           "re",
	"la réunion":                        "re",
	"sudan":                             "sd",
	"السودان":                           "sd",
	"tanzania":                          "tz",
	"u.s. virgin islands":               "vi",
	"united states virgin islands":      "vi",
	"christmas island":                  "cx",
	"dominica":                          "dm",
	"heard island and mcdonald islands": "hm",
	"laos":                              "la",
	"ສປປລາວ":                            "la",
	"luxembourg":                        "lu",
	"liechtenstein":                     "li",
	"turkmenistan":                      "tm",
	"türkmenistan":                      "tm",
	"argentina":                         "ar",
	"liberia":                           "lr",
	"malta":                             "mt",
	"pakistan":                          "pk",
	"uzbekistan":                        "uz",
	"o‘zbekiston":                       "uz",
	"armenia":                           "am",
	"հայաստան":                          "am",
	"gibraltar":                         "gi",
	"kazakhstan":                        "kz",
	"қазақстан":                         "kz",
	"nepal":                             "np",
	"नेपाल":                             "np",
	"qatar":                             "qa",
	"قطر":                               "qa",
	"rwanda":                            "rw",
	"seychelles":                        "sc",
	"cape verde":                        "cv",
	"cabo verde":                        "cv",
	"ghana":                             "gh",
	"slovakia":                          "sk",
	"slovensko":                         "sk",
	"togo":                              "tg",
	"japan":                             "jp",
	"日本":                                "jp",
	"new caledonia":                     "nc",
	"nouvelle-calédonie":                "nc",
	"romania":                           "ro",
	"românia":                           "ro",
	"taiwan":                            "tw",
	"臺灣":                                "tw",
	"united states":                     "us",
	"bosnia and herzegovina":            "ba",
	"bosna i hercegovina":               "ba",
	"bonaire":                           "bq",
	"croatia":                           "hr",
	"hrvatska":                          "hr",
	"mauritania":                        "mr",
	"موريتانيا":                         "mr",
	"singapore":                         "sg",
	"samoa":                             "ws",
	"uganda":                            "ug",
	"zambia":                            "zm",
	"saint barthelemy":                  "bl",
	"saint-barthélemy":                  "bl",
	"iraq":                              "iq",
	"العراق":                            "iq",
	"saint pierre and miquelon":         "pm",
	"saint-pierre-et-miquelon":          "pm",
	"paraguay":                          "py",
	"sint maarten":                      "sx",
	"canada":                            "ca",
	"czech republic":                    "cz",
	"česká republika":                   "cz",
	"north korea":                       "kp",
	"북한":                                "kp",
	"serbia":                            "rs",
	"србија":                            "rs",
	"somalia":                           "so",
	"soomaaliya":                        "so",
	"guyana":                            "gy",
	"french southern territories":       "tf",
	"territoire des terres australes et antarctiques fr": "tf",
	"tuvalu":                               "tv",
	"guinea":                               "gn",
	"guinée":                               "gn",
	"italy":                                "it",
	"italia":                               "it",
	"malawi":                               "mw",
	"palestine":                            "ps",
	"فلسطين":                               "ps",
	"afghanistan":                          "af",
	"افغانستان":                            "af",
	"eritrea":                              "er",
	"ኤርትራ":                                 "er",
	"burundi":                              "bi",
	"mexico":                               "mx",
	"méxico":                               "mx",
	"bangladesh":                           "bd",
	"north macedonia":                      "mk",
	"северна македонија":                   "mk",
	"northern mariana islands":             "mp",
	"greece":                               "gr",
	"ελλάδα":                               "gr",
	"honduras":                             "hn",
	"philippines":                          "ph",
	"pilipinas":                            "ph",
	"colombia":                             "co",
	"guatemala":                            "gt",
	"russia":                               "ru",
	"россия":                               "ru",
	"mayotte":                              "yt",
	"south africa":                         "za",
	"estonia":                              "ee",
	"eesti":                                "ee",
	"hungary":                              "hu",
	"magyarország":                         "hu",
	"latvia":                               "lv",
	"latvija":                              "lv",
	"namibia":                              "na",
	"netherlands":                          "nl",
	"nederland":                            "nl",
	"british virgin islands":               "vg",
	"vanuatu":                              "vu",
	"american samoa":                       "as",
	"barbados":                             "bb",
	"cuba":                                 "cu",
	"kiribati":                             "ki",
	"moldova":                              "md",
	"puerto rico":                          "pr",
	"bulgaria":                             "bg",
	"българия":                             "bg",
	"monaco":                               "mc",
	"nauru":                                "nr",
	"poland":                               "pl",
	"polska":                               "pl",
	"tokelau":                              "tk",
	"bhutan":                               "bt",
	"ʼbrug-yul":                            "bt",
	"azerbaijan":                           "az",
	"azərbaycan":                           "az",
	"madagascar":                           "mg",
	"madagasikara":                         "mg",
	"algeria":                              "dz",
	"الجزائر":                              "dz",
	"micronesia":                           "fm",
	"gabon":                                "ga",
	"slovenia":                             "si",
	"slovenija":                            "si",
	"u.s. minor outlying islands":          "um",
	"united states minor outlying islands": "um",
	"kosovo":                               "xk",
	"republika e kosovës":                  "xk",
	"usa":                                  "us",
}
