package geolabels

var countryLabelToCode = map[string]string{
	"benin":                                "bj",
	"bénin":                                "bj",
	"niue":                                 "nu",
	"niuē":                                 "nu",
	"palestine":                            "ps",
	"فلسطين":                               "ps",
	"togo":                                 "tg",
	"bonaire":                              "bq",
	"croatia":                              "hr",
	"hrvatska":                             "hr",
	"haiti":                                "ht",
	"haïti":                                "ht",
	"sierra leone":                         "sl",
	"united kingdom":                       "gb",
	"greece":                               "gr",
	"ελλάδα":                               "gr",
	"kuwait":                               "kw",
	"الكويت":                               "kw",
	"aruba":                                "aw",
	"comoros":                              "km",
	"komori":                               "km",
	"libya":                                "ly",
	"‏ليبيا":                               "ly",
	"north macedonia":                      "mk",
	"северна македонија":                   "mk",
	"maldives":                             "mv",
	"taiwan":                               "tw",
	"臺灣":                                   "tw",
	"kyrgyzstan":                           "kg",
	"кыргызстан":                           "kg",
	"saint kitts and nevis":                "kn",
	"sint maarten":                         "sx",
	"turks and caicos islands":             "tc",
	"andorra":                              "ad",
	"belarus":                              "by",
	"белару́сь":                            "by",
	"spain":                                "es",
	"españa":                               "es",
	"botswana":                             "bw",
	"gambia":                               "gm",
	"portugal":                             "pt",
	"latvia":                               "lv",
	"latvija":                              "lv",
	"uzbekistan":                           "uz",
	"o‘zbekiston":                          "uz",
	"denmark":                              "dk",
	"danmark":                              "dk",
	"senegal":                              "sn",
	"sénégal":                              "sn",
	"azerbaijan":                           "az",
	"azərbaycan":                           "az",
	"burkina faso":                         "bf",
	"ivory coast":                          "ci",
	"côte d'ivoire":                        "ci",
	"dominican republic":                   "do",
	"república dominicana":                 "do",
	"barbados":                             "bb",
	"qatar":                                "qa",
	"قطر":                                  "qa",
	"afghanistan":                          "af",
	"افغانستان":                            "af",
	"bangladesh":                           "bd",
	"nepal":                                "np",
	"नेपाल":                                "np",
	"mayotte":                              "yt",
	"cayman islands":                       "ky",
	"mauritania":                           "mr",
	"موريتانيا":                            "mr",
	"vanuatu":                              "vu",
	"singapore":                            "sg",
	"united states":                        "us",
	"israel":                               "il",
	"יִשְׂרָאֵל":                           "il",
	"jordan":                               "jo",
	"الأردن":                               "jo",
	"saudi arabia":                         "sa",
	"العربية السعودية":                     "sa",
	"peru":                                 "pe",
	"perú":                                 "pe",
	"vietnam":                              "vn",
	"việt nam":                             "vn",
	"austria":                              "at",
	"österreich":                           "at",
	"cocos (keeling) islands":              "cc",
	"cook islands":                         "ck",
	"estonia":                              "ee",
	"eesti":                                "ee",
	"honduras":                             "hn",
	"marshall islands":                     "mh",
	"m̧ajeļ":                               "mh",
	"sao tome and principe":                "st",
	"são tomé e príncipe":                  "st",
	"monaco":                               "mc",
	"nauru":                                "nr",
	"sweden":                               "se",
	"sverige":                              "se",
	"italy":                                "it",
	"italia":                               "it",
	"british virgin islands":               "vg",
	"wallis and futuna":                    "wf",
	"wallis et futuna":                     "wf",
	"myanmar (burma)":                      "mm",
	"မြန်မာ":                               "mm",
	"nigeria":                              "ng",
	"philippines":                          "ph",
	"pilipinas":                            "ph",
	"argentina":                            "ar",
	"germany":                              "de",
	"deutschland":                          "de",
	"kenya":                                "ke",
	"faroe islands":                        "fo",
	"føroyar":                              "fo",
	"chad":                                 "td",
	"tchad":                                "td",
	"trinidad and tobago":                  "tt",
	"curacao":                              "cw",
	"curaçao":                              "cw",
	"western sahara":                       "eh",
	"الصحراء الغربية":                      "eh",
	"heard island and mcdonald islands":    "hm",
	"u.s. virgin islands":                  "vi",
	"united states virgin islands":         "vi",
	"armenia":                              "am",
	"հայաստան":                             "am",
	"montenegro":                           "me",
	"црна гора":                            "me",
	"syria":                                "sy",
	"سوريا":                                "sy",
	"north korea":                          "kp",
	"북한":                                   "kp",
	"cambodia":                             "kh",
	"kâmpŭchéa":                            "kh",
	"mauritius":                            "mu",
	"maurice":                              "mu",
	"bahrain":                              "bh",
	"‏البحرين":                             "bh",
	"canada":                               "ca",
	"finland":                              "fi",
	"suomi":                                "fi",
	"somalia":                              "so",
	"soomaaliya":                           "so",
	"tokelau":                              "tk",
	"turkmenistan":                         "tm",
	"türkmenistan":                         "tm",
	"u.s. minor outlying islands":          "um",
	"united states minor outlying islands": "um",
	"yemen":                                "ye",
	"اليَمَن":                              "ye",
	"fiji":                                 "fj",
	"south georgia and the south sandwich islands": "gs",
	"south georgia":        "gs",
	"moldova":              "md",
	"jamaica":              "jm",
	"laos":                 "la",
	"ສປປລາວ":               "la",
	"papua new guinea":     "pg",
	"papua niugini":        "pg",
	"rwanda":               "rw",
	"cyprus":               "cy",
	"κύπρος":               "cy",
	"eritrea":              "er",
	"ኤርትራ":                 "er",
	"guinea":               "gn",
	"guinée":               "gn",
	"san marino":           "sm",
	"united arab emirates": "ae",
	"دولة الإمارات العربية المتحدة": "ae",
	"burundi":                          "bi",
	"bouvet island":                    "bv",
	"bouvetøya":                        "bv",
	"kazakhstan":                       "kz",
	"қазақстан":                        "kz",
	"martinique":                       "mq",
	"brunei":                           "bn",
	"negara brunei darussalam":         "bn",
	"grenada":                          "gd",
	"guyana":                           "gy",
	"democratic republic of the congo": "cd",
	"république démocratique du congo": "cd",
	"malawi":                           "mw",
	"bulgaria":                         "bg",
	"българия":                         "bg",
	"macao":                            "mo",
	"澳門":                               "mo",
	"uruguay":                          "uy",
	"chile":                            "cl",
	"luxembourg":                       "lu",
	"norway":                           "no",
	"norge":                            "no",
	"lebanon":                          "lb",
	"لبنان":                            "lb",
	"belize":                           "bz",
	"gabon":                            "ga",
	"ghana":                            "gh",
	"sri lanka":                        "lk",
	"śrī laṃkāva":                      "lk",
	"nicaragua":                        "ni",
	"belgium":                          "be",
	"belgië":                           "be",
	"dominica":                         "dm",
	"iceland":                          "is",
	"ísland":                           "is",
	"bermuda":                          "bm",
	"slovenia":                         "si",
	"slovenija":                        "si",
	"morocco":                          "ma",
	"المغرب":                           "ma",
	"romania":                          "ro",
	"românia":                          "ro",
	"tunisia":                          "tn",
	"تونس":                             "tn",
	"zambia":                           "zm",
	"republic of the congo":            "cg",
	"république du congo":              "cg",
	"iran":                             "ir",
	"ایران":                            "ir",
	"liberia":                          "lr",
	"lesotho":                          "ls",
	"new zealand":                      "nz",
	"paraguay":                         "py",
	"tonga":                            "to",
	"vatican city":                     "va",
	"vaticano":                         "va",
	"samoa":                            "ws",
	"niger":                            "ne",
	"serbia":                           "rs",
	"србија":                           "rs",
	"slovakia":                         "sk",
	"slovensko":                        "sk",
	"jersey":                           "je",
	"suriname":                         "sr",
	"albania":                          "al",
	"shqipëria":                        "al",
	"guernsey":                         "gg",
	"gibraltar":                        "gi",
	"algeria":                          "dz",
	"الجزائر":                          "dz",
	"egypt":                            "eg",
	"مصر‎":                             "eg",
	"northern mariana islands":         "mp",
	"panama":                           "pa",
	"panamá":                           "pa",
	"reunion":                          "re",
	"la réunion":                       "re",
	"bahamas":                          "bs",
	"costa rica":                       "cr",
	"norfolk island":                   "nf",
	"saint vincent and the grenadines": "vc",
	"bosnia and herzegovina":           "ba",
	"bosna i hercegovina":              "ba",
	"china":                            "cn",
	"中国":                               "cn",
	"lithuania":                        "lt",
	"lietuva":                          "lt",
	"american samoa":                   "as",
	"ecuador":                          "ec",
	"guatemala":                        "gt",
	"south korea":                      "kr",
	"대한민국":                             "kr",
	"anguilla":                         "ai",
	"cape verde":                       "cv",
	"cabo verde":                       "cv",
	"czech republic":                   "cz",
	"česká republika":                  "cz",
	"new caledonia":                    "nc",
	"nouvelle-calédonie":               "nc",
	"russia":                           "ru",
	"россия":                           "ru",
	"georgia":                          "ge",
	"საქართველო":                       "ge",
	"japan":                            "jp",
	"日本":                               "jp",
	"saint pierre and miquelon":        "pm",
	"saint-pierre-et-miquelon":         "pm",
	"east timor":                       "tl",
	"timor-leste":                      "tl",
	"france":                           "fr",
	"hungary":                          "hu",
	"magyarország":                     "hu",
	"mali":                             "ml",
	"thailand":                         "th",
	"ประเทศไทย":                        "th",
	"british indian ocean territory":   "io",
	"iraq":                             "iq",
	"العراق":                           "iq",
	"french polynesia":                 "pf",
	"polynésie française":              "pf",
	"micronesia":                       "fm",
	"montserrat":                       "ms",
	"saint helena":                     "sh",
	"brazil":                           "br",
	"brasil":                           "br",
	"mozambique":                       "mz",
	"moçambique":                       "mz",
	"french southern territories":      "tf",
	"territoire des terres australes et antarctiques fr": "tf",
	"ukraine":                  "ua",
	"україна":                  "ua",
	"saint lucia":              "lc",
	"puerto rico":              "pr",
	"south sudan":              "ss",
	"netherlands":              "nl",
	"nederland":                "nl",
	"turkey":                   "tr",
	"türkiye":                  "tr",
	"australia":                "au",
	"christmas island":         "cx",
	"india":                    "in",
	"भारत":                     "in",
	"ireland":                  "ie",
	"éire":                     "ie",
	"mexico":                   "mx",
	"méxico":                   "mx",
	"tuvalu":                   "tv",
	"guadeloupe":               "gp",
	"oman":                     "om",
	"عمان":                     "om",
	"palau":                    "pw",
	"angola":                   "ao",
	"bolivia":                  "bo",
	"bhutan":                   "bt",
	"ʼbrug-yul":                "bt",
	"madagascar":               "mg",
	"madagasikara":             "mg",
	"solomon islands":          "sb",
	"cameroon":                 "cm",
	"isle of man":              "im",
	"liechtenstein":            "li",
	"indonesia":                "id",
	"eswatini":                 "sz",
	"uganda":                   "ug",
	"antigua and barbuda":      "ag",
	"guam":                     "gu",
	"hong kong":                "hk",
	"香港":                       "hk",
	"switzerland":              "ch",
	"schweiz":                  "ch",
	"cuba":                     "cu",
	"guinea-bissau":            "gw",
	"guiné-bissau":             "gw",
	"el salvador":              "sv",
	"venezuela":                "ve",
	"central african republic": "cf",
	"ködörösêse tî bêafrîka":   "cf",
	"namibia":                  "na",
	"pitcairn islands":         "pn",
	"poland":                   "pl",
	"polska":                   "pl",
	"sudan":                    "sd",
	"السودان":                  "sd",
	"kosovo":                   "xk",
	"republika e kosovës":      "xk",
	"antarctica":               "aq",
	"aland":                    "ax",
	"åland":                    "ax",
	"djibouti":                 "dj",
	"malta":                    "mt",
	"malaysia":                 "my",
	"seychelles":               "sc",
	"zimbabwe":                 "zw",
	"colombia":                 "co",
	"french guiana":            "gf",
	"guyane française":         "gf",
	"equatorial guinea":        "gq",
	"guinea ecuatorial":        "gq",
	"kiribati":                 "ki",
	"saint martin":             "mf",
	"saint-martin":             "mf",
	"saint barthelemy":         "bl",
	"saint-barthélemy":         "bl",
	"ethiopia":                 "et",
	"ኢትዮጵያ":                    "et",
	"south africa":             "za",
	"greenland":                "gl",
	"kalaallit nunaat":         "gl",
	"mongolia":                 "mn",
	"монгол улс":               "mn",
	"tajikistan":               "tj",
	"тоҷикистон":               "tj",
	"tanzania":                 "tz",
	"falkland islands":         "fk",
	"pakistan":                 "pk",
	"svalbard and jan mayen":   "sj",
	"svalbard og jan mayen":    "sj",
}
