name: Docker build of the API

# on: push
on:
  push:
    tags:        
        - '*'
        - '!latest'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Mokto
          password: ${{ secrets.PACKAGES_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/mokto/opengeocoding-api

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          platforms: linux/amd64
          # ,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/mokto/opengeocoding-api:latest
            ghcr.io/mokto/opengeocoding-api:${{github.ref_name}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.PACKAGES_PAT }}"
          prerelease: false
          files: |
            LICENSE
